version: '3.9'

services:
  database:
    image: 'postgres:17'
    container_name: 'notes_sync_database'
    profiles: [services, all]
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_PATH}
      POSTGRES_PORT: ${DB_PORT}
    networks:
      - database
    ports:
      - "${DB_PORT}:${DB_PORT}"
  # Message broking
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.7.1'
    container_name: 'notes_sync_zookeeper'
    profiles: [services, all]
    networks:
      - broker
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: 'confluentinc/cp-kafka:7.7.1'
    container_name: 'notes_sync_broker'
    profiles: [services, all]
    networks:
      - broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST}:9092
      KAFKA_ZOOKEEPER_CONNECT: notes_sync_zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOST}:${KAFKA_PORT},PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  kafdrop:
    image: 'obsidiandynamics/kafdrop:4.0.2'
    container_name: 'notes_sync_kafdrop'
    profiles: [services, all]
    networks:
      - broker
    depends_on:
      - zookeeper
      - broker
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: ${KAFKA_HOST}:${KAFKA_PORT}
  server:
    image: 'notes_sync_server'
    container_name: 'notes_sync_server_container'
    profiles: [services, all]
    networks:
      - database
      - broker
    depends_on:
      - database
      - broker
    ports:
      - "${API_PORT}:${API_PORT}"
  health_check_consumer:
    image: 'notes_sync_health_check_consumer'
    container_name: 'notes_sync_health_check_consumer_container'
    profiles: [consumers, all]
    networks:
      - broker
    depends_on:
      - broker
  logsequence_consumer:
    image: 'notes_sync_logsequence_consumer'
    container_name: 'notes_sync_logsequence_consumer_container'
    profiles: [consumers, all]
    networks:
      - database
      - broker
    depends_on:
      - database
      - broker

networks:
  database:
    driver: bridge
  broker:
    driver: bridge