version: '3.9'

services:
  db:
    image: 'postgres:17'
    container_name: 'notes_sync_db'
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_PATH}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    network_mode: host
  # Message broking
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.7.1'
    container_name: 'notes_sync_zookeeper'
    networks:
      - broker
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: 'confluentinc/cp-kafka:7.7.1'
    container_name: 'notes_sync_kafka'
    networks:
      - broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: notes_sync_kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: notes_sync_zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://notes_sync_kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  kafdrop:
    image: 'obsidiandynamics/kafdrop:4.0.2'
    container_name: 'notes_sync_kafdrop'
    networks:
      - broker
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: notes_sync_kafka:29092

networks:
  broker:
    driver: bridge