"""empty message

Revision ID: 480c5e136794
Revises: 43b51052938e
Create Date: 2024-12-01 18:06:54.925503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "480c5e136794"
down_revision: Union[str, None] = "43b51052938e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "logsequence_message", sa.Column("user", sa.Integer(), nullable=False)
    )
    op.drop_index("ix__logsequence_message__token", table_name="logsequence_message")
    op.create_index(
        op.f("ix__logsequence_message__user"),
        "logsequence_message",
        ["user"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk__logsequence_message__user__user"),
        "logsequence_message",
        "user",
        ["user"],
        ["id"],
    )
    op.drop_column("logsequence_message", "token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "logsequence_message",
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk__logsequence_message__user__user"),
        "logsequence_message",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix__logsequence_message__user"), table_name="logsequence_message"
    )
    op.create_index(
        "ix__logsequence_message__token", "logsequence_message", ["token"], unique=False
    )
    op.drop_column("logsequence_message", "user")
    # ### end Alembic commands ###
