"""Generate LogsequenceMessage table

Revision ID: 54ff0821c1f4
Revises:
Create Date: 2024-11-18 20:46:15.408069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54ff0821c1f4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logsequence_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__logsequence_message")),
    )
    op.create_index(
        op.f("ix__logsequence_message__id"), "logsequence_message", ["id"], unique=False
    )
    op.create_index(
        op.f("ix__logsequence_message__token"),
        "logsequence_message",
        ["token"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__logsequence_message__token"), table_name="logsequence_message"
    )
    op.drop_index(op.f("ix__logsequence_message__id"), table_name="logsequence_message")
    op.drop_table("logsequence_message")
    # ### end Alembic commands ###
