"""empty message

Revision ID: 7937ed15cce9
Revises: f4baa303fb4c
Create Date: 2024-11-26 21:18:59.811126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7937ed15cce9"
down_revision: Union[str, None] = "f4baa303fb4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_defaults",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("pk__config_defaults")),
    )
    op.create_index(
        op.f("ix__config_defaults__name"), "config_defaults", ["name"], unique=False
    )
    op.create_table(
        "config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk__config__user_id__user")
        ),
        sa.PrimaryKeyConstraint("id", "user_id", name=op.f("pk__config")),
    )
    op.create_index(op.f("ix__config__id"), "config", ["id"], unique=False)
    op.create_index(op.f("ix__config__name"), "config", ["name"], unique=True)
    op.create_index(op.f("ix__config__user_id"), "config", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__config__user_id"), table_name="config")
    op.drop_index(op.f("ix__config__name"), table_name="config")
    op.drop_index(op.f("ix__config__id"), table_name="config")
    op.drop_table("config")
    op.drop_index(op.f("ix__config_defaults__name"), table_name="config_defaults")
    op.drop_table("config_defaults")
    # ### end Alembic commands ###
