"""Implement User model

Revision ID: f4baa303fb4c
Revises: 54ff0821c1f4
Create Date: 2024-11-20 23:10:09.133073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4baa303fb4c"
down_revision: Union[str, None] = "54ff0821c1f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("pass_hash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user")),
    )
    op.create_index(op.f("ix__user__id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix__user__pass_hash"), "user", ["pass_hash"], unique=False)
    op.create_index(op.f("ix__user__username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__user__username"), table_name="user")
    op.drop_index(op.f("ix__user__pass_hash"), table_name="user")
    op.drop_index(op.f("ix__user__id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
